package ru.geekbrains.kotlin.base.data.errors

class NoAuthException: Throwable() {

}